language: rust

os:
  - linux
  - osx
  - windows

rust: nightly

env:
  - RUSTFLAGS="-D warnings"
  - CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="valgrind --leak-check=full --error-exitcode=1"

addons:
  apt:
    packages:
      - valgrind

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo check --benches --bins --examples --tests
  - cargo test -- --test-threads=1
  - cargo check --no-default-features
