language: rust
rust:
  - 1.0.0
  - 1.5.0
  - 1.10.0
  - 1.15.0
  - 1.20.0
  - 1.25.0
  - 1.30.0
  - 1.35.0
  - 1.40.0
  - stable
  - beta
  - nightly

matrix:
  include:
    # try probing a target that doesn't have std at all
    - name: "no_std"
      rust: stable
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add $TARGET
      script:
        - cargo test --verbose --lib
    # we don't even need an installed target for version checks
    - name: "missing_target"
      rust: stable
      env: TARGET=thumbv6m-none-eabi
      script:
        - cargo test --verbose --lib -- version
    - name: "rustfmt"
      rust: 1.31.0
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

notifications:
  email:
    on_success: never
