#![allow(unused, missing_docs)]
/// declare module generated by the build script.
use shadow_rs::shadow;
shadow!(shadow);

/// get commit hash of this build.
pub fn short() -> String {
    format!("{} - {}", shadow::PKG_VERSION, shadow::SHORT_COMMIT)
}

/// get more complete information about this build.
pub fn long() -> String {
    format!(
        "version = {}\nbranch = {}\ncommit_hash = {}\nbuild_time = {}\nrustc_version = {}\nrust_toolchain = {}",
        shadow::PKG_VERSION,
        shadow::BRANCH,
        shadow::COMMIT_HASH,
        shadow::BUILD_TIME,
        shadow::RUST_VERSION,
        shadow::RUST_CHANNEL,
    )
}
