version: 2
jobs:
  build:
    docker:
      - image: xd009642/tarpaulin
    steps:
      - checkout
      - run:
          name: Generate coverage report
          command: cargo tarpaulin --out Xml --all-features
      - run:
          name: Upload to codecov.io
          command: bash <(curl -s https://codecov.io/bash) -Z -f cobertura.xml
