language: rust
sudo: false

# run builds for all the trains (and more)
rust:
  - 1.12.0
  - stable
  - beta
  - nightly

branches:
  only:
    - master
# the main build
script:
  - |
      cargo build --features "${FEATURES}" &&
      cargo test --features "${FEATURES}" &&
      cargo doc --features "${FEATURES}"

env:
  matrix:
    - FEATURES=""
    - FEATURES="serde"

matrix:
  exclude:
    - rust: 1.12.0
      env: FEATURES="serde"
