sudo: false
language: rust
cache:
  cargo: true
matrix:
  include:
  - rust: 1.19.0  # Oldest supported (first version with numeric fields in struct patterns)
  - rust: 1.31.0  # Oldest supported with allow(clippy)
  - rust: 1.36.0  # Oldest supported with MaybeUninit
  - rust: stable
  - rust: beta
  - rust: nightly

  - env: MIRI
    rust: nightly
    os: linux
    script:
      - sh ci/miri.sh

  - env: CONST_OFFSET
    rust: nightly
    os: linux
    script:  # `--lib` added to prevent doctests from being compiled.
             # This is due to `unstable_const` requiring extra `feature(...)` directives
             # which the doctests do not have.
      - cargo test --verbose --features unstable_const --lib

  - env: RUSTFMT
    rust: 1.36.0
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt -- --check

  - env: RUSTFLAGS="-D warnings"
    rust: 1.33.0  # `stable`: Locking down for consistent behavior
    script:
    - cargo check --tests

install:
- rustc -Vv
- cargo -V

script:
- rm -rf target/debug/deps/*memoffset*  # Avoid rustdoc problems
- cargo test --verbose
