os:
  - linux
  - mac
  - windows
sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.34.0
matrix:
  include:
    - os: linux
      rust: stable-i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-multilib
script:
  - cargo check --no-default-features
  - cargo check --no-default-features --features enable_unstable_features_that_may_break_with_minor_version_bumps
  - cargo check --no-default-features --features serde
  - cargo check --all-features
  - cargo test --all-features
  - cargo test --release --all-features
