codecov:
  # Do not wait for these CI providers since they will not upload any
  # coverage reports.
  ci:
    - !appveyor
    - !travis

coverage:
  status:
    project:
      default:
        # Allow a 5% drop in overall project coverage on a PR.
        threshold: 5%
