language: rust
sudo: false
dist: trusty

rust:
    - nightly
    - beta
    - stable

env:
    -
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD=1
    - CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1 RUSTFLAGS="-C target_feature=+sse4.2"
    - RUSTFLAGS="-C target_feature=+sse4.2"

matrix:
    fast_finish: true
    include:
        - rust: 1.10.0 # minimum Rust version
          script: # don't run tests, since dev-dependencies don't build on 1.10
              - cargo build --no-default-features
              - cargo build

        # with sudo the worker has avx2 support
        - rust: nightly
          sudo: true
          env: RUSTFLAGS="-C target_feature=+avx2"
        - rust: nightly
          sudo: true
          env: RUSTFLAGS="-C target_feature=sse4.2"
        - rust: nightly
          sudo: true
          env: RUSTFLAGS="-C target_feature=+sse4.2,+avx2"
        - rust: nightly
          sudo: true
          env: CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1 RUSTFLAGS="-C target_feature=+sse4.2,+avx2"

        - rust: beta
          sudo: true
          env: RUSTFLAGS="-C target_feature=+avx2"
        - rust: beta
          sudo: true
          env: RUSTFLAGS="-C target_feature=+sse4.2"
        - rust: beta
          sudo: true
          env: RUSTFLAGS="-C target_feature=+sse4.2,+avx2"
        - rust: beta
          sudo: true
          env: CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1 RUSTFLAGS="-C target_feature=+sse4.2,+avx2"

        - rust: stable
          sudo: true
          env: RUSTFLAGS="-C target_feature=+avx2"
        - rust: stable
          sudo: true
          env: RUSTFLAGS="-C target_feature=+sse4.2"
        - rust: stable
          sudo: true
          env: RUSTFLAGS="-C target_feature=+sse4.2,+avx2"
        - rust: stable
          sudo: true
          env: CARGO_CFG_HTTPARSE_DISABLE_SIMD_COMPILETIME=1 RUSTFLAGS="-C target_feature=+sse4.2,+avx2"

script:
    - cargo build --no-default-features
    - cargo test --no-default-features
    - cargo build
    - cargo test

