name: Security audit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set current week of the year in environnement
        run: echo "::set-env name=CURRENT_WEEK::$(date +%V)"
      
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
