version: 2

jobs:
  build:
    docker:
      - image: rust:1.36.0
    steps:
      - checkout
      - restore_cache:
          key: registry
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ epoch }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          key: dependencies-1.36-{{ checksum "Cargo.lock" }}
      - run: cargo test
      - save_cache:
          key: dependencies-1.36-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo/registry/cache
