language: rust
matrix:
  include:
    - rust: 1.30.0
    - rust: stable
      env: RUST_STABLE=1
    - rust: beta
    - rust: nightly
    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master

before_script:
  - rustup component add rustfmt-preview
script:
  - |
    if [ "$RUST_STABLE" = 1 ]; then
      cargo fmt --all -- --check
    fi
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email:
    on_success: never
