language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - cargo build
  - cargo doc
  - "cargo test --features 'encoding encoding_rs'"
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo test --features bench; fi"
  - "if [ $TRAVIS_RUST_VERSION = nightly ]; then (cd capi/ctest; ./build-and-test.sh); fi"
notifications:
  webhooks: http://build.servo.org:54856/travis
